### ISSUE TITLE
No text above spoilers

### ISSUE THREAD

**Issue by okazakikun** [TimboKZ/discord-spoiler-bot#15]
Unable to figure out this one. Using node 7.10.0  NPM 4.5.0
What it looks like [here](http://puu.sh/vOXjV/13f26048f8.png)
)```
user@user:~/discord$ node index.js --trace-warnings
Discord Spoiler Bot is running...
(node:90827) DeprecationWarning: TextChannel#sendFile: use TextChannel#send instead
(node:90827) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DiscordAPIError: Unknown Message
(node:90827) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by vegeta897** [comment]
Perhaps an unsupported update to [Discord.js](https://discord.js.org/#/)?

**Comment by okazakikun** [comment]
Any idea what version is supported?
using version 11.1.0

**Comment by TimboKZ** [comment]
Give me a moment; I'm currently looking into this issue, will update you ASAP.

**Comment by TimboKZ** [comment]
Try installing the package below by hand. This might fix your issue though I am not quite sure yet what caused it in the first place.

https://github.com/TimboKZ/discord-spoiler-bot/releases/download/2.0.4-beta/discord-spoiler-bot-2.0.4.tgz

To install it, place the `tgz` file in your project directory and run `npm install --save discord-spoiler-bot-2.0.4.tgz`.

If this will work for you I will release it on NPM.

**Comment by okazakikun** [comment]
Works perfectly now, only issue i have now is marking others spoilers, [here](http://puu.sh/vP4HH/04bb264a9e.png)

my index.js is

```
'use strict';

const SpoilerBot = require('discord-spoiler-bot');

let config = {
    token: 'MzEzMDE2NzExNzgxODEwMTc4.C_jfCg.bCClmp8Mw6jW4QYOwg-mWoHNv60',
    markAllowAllow: true,
};

let bot = new SpoilerBot(config);
bot.connect();

```

apologies if i'm being stupid about this and have misread the docs.

**Comment by okazakikun** [comment]
Works perfectly now, only issue i have now is marking others spoilers, [here](http://puu.sh/vP4HH/04bb264a9e.png)

my index.js is

```
'use strict';

const SpoilerBot = require('discord-spoiler-bot');

let config = {
    token: 'secret',
    markAllowAllow: true,
};

let bot = new SpoilerBot(config);
bot.connect();

```

apologies if i'm being stupid about this and have misread the docs. 


[Re-posted to take out my secret]

**Comment by TimboKZ** [comment]
My apologies, there was a typo in the wiki. 2nd line of the config should say `markAllowAll` and **not** `markAllowAllow`.

**Comment by okazakikun** [comment]
I honestly don't know how i didn't spot that :) thanks

**Comment by TimboKZ** [comment]
Good to hear you're all sorted. I'm closing this issue and will release v2.0.4 on NPM in a couple of minutes.
