### ISSUE TITLE
Allow SPOILER_MESSAGE customization

### ISSUE THREAD

**Issue by qgustavor** [TimboKZ/discord-spoiler-bot#17]
`SPOILER_MESSAGE` [is hardcoded here](https://github.com/TimboKZ/discord-spoiler-bot/blob/0b18087808af8f630fb94ede085aed32c4611643/src/GifGenerator.js#L25). Allowing it to be changed will also allow it to be easily translated.

**Comment by TimboKZ** [comment]
That's a good suggestion, cheers! I'm travelling at the moment but as soon as I'll have a free moment I'll extend the config and update the wiki.

**Comment by TimboKZ** [comment]
Apologies for the delay, was extremely busy for the last couple of weeks. GIF customisation has now been implemented (#18), make sure to update to v2.0.5 and check [relevant wiki sections](https://github.com/TimboKZ/discord-spoiler-bot/wiki/Usage#custom-spoiler-gif-appearance).
