### ISSUE TITLE
[Suggestion] Set bot presence/game as spoiler syntax

### ISSUE THREAD

**Issue by ericalle** [TimboKZ/discord-spoiler-bot#21]
In the config allow for the end user to supply a "game" for discord to play. This will allow it to show underneath the Name in the member's list of the server.

For Example:
Spoiler Bot
Playing [TOPIC]:spoiler:[TEXT]

**Comment by TimboKZ** [comment]
Sounds like a great idea, will implement it sometime soon.

For the time being you could [use an external bot instance](https://github.com/TimboKZ/discord-spoiler-bot/wiki/Usage#using-external-bot-instance) and specify the game manually.

**Comment by TimboKZ** [comment]
Implemented in `v2.0.6`.
