### ISSUE TITLE
Can't install the version of erlpack required

### ISSUE THREAD

**Issue by ghost** [TimboKZ/discord-spoiler-bot#22]
```
PS C:\SpoilerBot> npm install discord-spoiler-bot --save
spoilerbot@1.0.0 C:\SpoilerBot
-- discord-spoiler-bot@2.0.5
-- UNMET PEER DEPENDENCY erlpack@hammerandchisel/erlpack

npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
non WARN spoilerbot@1.0.0 No description
npm WARN spoilerbot@1.0.0 No repository field.
```

I got all the other peer dependencies installed, but I can't manage to get this one.

**Comment by TimboKZ** [comment]
Do you get any errors when you try to run the bot?

**Comment by ghost** [comment]
Haven't tried to run it, as I get an error when I try to install this. Are you saying that it installs regardless of the error?

**Comment by TimboKZ** [comment]
Sometimes peer dependencies are not required, but I can’t recall if that’s the case with this particular one. Try running the bot.

**Comment by ghost** [comment]
It works! Great bot btw 👍

**Comment by TimboKZ** [comment]
Glad to hear that, and thanks. Closing the issue.
