### ISSUE TITLE
Can't put emoji/images/gifs in spoiler

### ISSUE THREAD

**Issue by Kryod** [TimboKZ/discord-spoiler-bot#23]
Everything is in the title, emoji are replaced by encoding errors (I think), and images and gifs just don't work. I believe it should be possible to have an image or a gif marked as spoiler because of obvious reasons so yeah... I believe theses could be enhancement for your bot.

**Comment by TimboKZ** [comment]
Image spoilers are now implemented in Discord natively (see attached picture), so this is not relevant anymore. Closing.
![Image spoilers in Discord](https://user-images.githubusercontent.com/5504588/55691357-6c17a980-5995-11e9-86ae-5e31a3c7a995.png)
